require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MainoptionsController do

  # This should return the minimal set of attributes required to create a valid
  # Mainoption. As you add validations to Mainoption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MainoptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mainoptions as @mainoptions" do
      mainoption = Mainoption.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mainoptions).should eq([mainoption])
    end
  end

  describe "GET show" do
    it "assigns the requested mainoption as @mainoption" do
      mainoption = Mainoption.create! valid_attributes
      get :show, {:id => mainoption.to_param}, valid_session
      assigns(:mainoption).should eq(mainoption)
    end
  end

  describe "GET new" do
    it "assigns a new mainoption as @mainoption" do
      get :new, {}, valid_session
      assigns(:mainoption).should be_a_new(Mainoption)
    end
  end

  describe "GET edit" do
    it "assigns the requested mainoption as @mainoption" do
      mainoption = Mainoption.create! valid_attributes
      get :edit, {:id => mainoption.to_param}, valid_session
      assigns(:mainoption).should eq(mainoption)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mainoption" do
        expect {
          post :create, {:mainoption => valid_attributes}, valid_session
        }.to change(Mainoption, :count).by(1)
      end

      it "assigns a newly created mainoption as @mainoption" do
        post :create, {:mainoption => valid_attributes}, valid_session
        assigns(:mainoption).should be_a(Mainoption)
        assigns(:mainoption).should be_persisted
      end

      it "redirects to the created mainoption" do
        post :create, {:mainoption => valid_attributes}, valid_session
        response.should redirect_to(Mainoption.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mainoption as @mainoption" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mainoption.any_instance.stub(:save).and_return(false)
        post :create, {:mainoption => { "name" => "invalid value" }}, valid_session
        assigns(:mainoption).should be_a_new(Mainoption)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mainoption.any_instance.stub(:save).and_return(false)
        post :create, {:mainoption => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mainoption" do
        mainoption = Mainoption.create! valid_attributes
        # Assuming there are no other mainoptions in the database, this
        # specifies that the Mainoption created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mainoption.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => mainoption.to_param, :mainoption => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested mainoption as @mainoption" do
        mainoption = Mainoption.create! valid_attributes
        put :update, {:id => mainoption.to_param, :mainoption => valid_attributes}, valid_session
        assigns(:mainoption).should eq(mainoption)
      end

      it "redirects to the mainoption" do
        mainoption = Mainoption.create! valid_attributes
        put :update, {:id => mainoption.to_param, :mainoption => valid_attributes}, valid_session
        response.should redirect_to(mainoption)
      end
    end

    describe "with invalid params" do
      it "assigns the mainoption as @mainoption" do
        mainoption = Mainoption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mainoption.any_instance.stub(:save).and_return(false)
        put :update, {:id => mainoption.to_param, :mainoption => { "name" => "invalid value" }}, valid_session
        assigns(:mainoption).should eq(mainoption)
      end

      it "re-renders the 'edit' template" do
        mainoption = Mainoption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mainoption.any_instance.stub(:save).and_return(false)
        put :update, {:id => mainoption.to_param, :mainoption => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mainoption" do
      mainoption = Mainoption.create! valid_attributes
      expect {
        delete :destroy, {:id => mainoption.to_param}, valid_session
      }.to change(Mainoption, :count).by(-1)
    end

    it "redirects to the mainoptions list" do
      mainoption = Mainoption.create! valid_attributes
      delete :destroy, {:id => mainoption.to_param}, valid_session
      response.should redirect_to(mainoptions_url)
    end
  end

end
